server:
  port: 8080

management:
  port: 8080
  context-path: "/management"

spring:
  aop:
    auto: true
    proxy-target-class: true


eureka:
  healthcheck:
    enabled: true
  instance:
    prefer-ip-address: true
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: "http://localhost:${server.port}/eureka"